### ISSUE TITLE
Astropy Partnership: TODO list

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/software-peer-review#276]
This issue is a TODO list for all the things we are collectively doing to kick off the astropy partnership 

pyOpenSci actions

- [x] Merge this pr which adds the astropy criteria to our peer review guide: https://github.com/pyOpenSci/software-peer-review/pull/225

## Website work
- [ ] [Address web development items outlines in this issue by @willingc ](https://github.com/pyOpenSci/software-peer-review/pull/258#issuecomment-1852828861)
- [ ] Get approval and merge new astropy landing page on our website: https://github.com/pyOpenSci/pyopensci.github.io/pull/207 : here we just want the astropy community to be ok with the text and graphics on the page. it can be simple and it can happen after our first review or two given there are no packages to populate it yet. 

On the astropy side of things:

- [ ] [Astropy feed update](https://github.com/astropy/astropy.github.com/issues/570) -  Astropy will pull their package listing from our list of packages which is [here](https://github.com/pyOpenSci/pyopensci.github.io/blob/main/_data/packages.yml) 
- [x] To support this work on the pyOpenSci side of things we need to 
- [x] Update our review template to include astropy and sunpy checkboxes
- [x] Update our review-metadata package to pull partnership information from a review submission

- [x] https://github.com/astropy/astropy.github.com/pull/573 - astropy affiliated text update

**Comment by pllim** [comment]
https://github.com/astropy/astropy.github.com/pull/573 is merged. FYI.

**Comment by lwasser** [comment]
@pllim i am going to close this. i think generally everything that immediately needed to happen is done. i think there are a few lingering items that we can work on separately

1. updating the astropy website. this might involve you manually doing it for a bit of time until there is an easier way to parse our yaml files. 
2. Creating an astropy landing page on our website. i think this will make more sense to do once we have more packages in our list. right now we only have one - zodipy. with martini in review. i'll close this for now and we can reopen a fresh issue when we're ready to tackle phase b which is co-listing packages on both websites.
